name: Auto deployment to GitHub pages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Ruby
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x
    - name: Setup Ruby dependencies
      run: bundle install --jobs 4 --retry 3
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        version: 6.11.4
    - name: Setup Node Dependencies
      run: yarn install
    - name: Import and symlink project docsites
      run: bundle exec rake projects:symlink
    - name: Build Middleman site
      run: bundle exec middleman build
    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v1.1.0
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs
